In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aswin\appdata\roaming\python\python312\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aswin\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\aswin\appdata\roaming\python\python312\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\aswin\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.8 MB 16.8 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 27.2 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 25.3 MB/s eta 0:00:00
Installing collected packages: pandas
Successfully installed pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [105]:
import pandas as pd

# Read CSV
df = pd.read_csv("titanic.csv")

# Replace missing values in Age with "N/A"
df["Age"] = df["Age"].fillna("N/A")

# Check the result
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,N/A,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [21]:
import pandas as pd

# Read original CSV
df = pd.read_csv("titanic.csv")

# Rename column
df.rename(columns={"PassengerId": "Id"}, inplace=True)

# Convert 0/1 to False/True strings
df["Survived"] = df["Survived"].replace({
    0: "False",
    1: "True"
})

# Replace all missing values with N/A
df = df.fillna("N/A")

# Output file path
output_file = r"C:\Development\AI-Engineer-GenAI-Developer-Roadmap\Topics\pandas\cleaned\cleaned_titanic.csv"

# Save cleaned CSV
df.to_csv(output_file, index=False,columns=["Id", "Survived", "Name","Age","Sex","Ticket","Fare"])

# Read the SAME file back
cleaned_df = pd.read_csv(
    output_file,
    keep_default_na=False
)

# Display DataFrame
cleaned_df

,Id,Survived,Name,Age,Sex,Ticket,Fare
0,1,False,"Braund, Mr. Owen Harris",22.0,male,A/5 21171,7.2500
1,2,True,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,PC 17599,71.2833
2,3,True,"Heikkinen, Miss. Laina",26.0,female,STON/O2. 3101282,7.9250
3,4,True,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,113803,53.1000
4,5,False,"Allen, Mr. William Henry",35.0,male,373450,8.0500
...,...,...,...,...,...,...,...
886,887,False,"Montvila, Rev. Juozas",27.0,male,211536,13.0000
887,888,True,"Graham, Miss. Margaret Edith",19.0,female,112053,30.0000
888,889,False,"Johnston, Miss. Catherine Helen ""Carrie""",N/A,female,W./C. 6607,23.4500
889,890,True,"Behr, Mr. Karl Howell",26.0,male,111369,30.0000
890,891,False,"Dooley, Mr. Patrick",32.0,male,370376,7.7500